//
// Copyright © 2018 Scriptinator (support@scriptinator.io)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Structure

The structure of a cron expression can be displayed like this:

 ┌─────────────── second       (0 - 59)
 │ ┌───────────── minute       (0 - 59)
 │ │ ┌─────────── hour         (0 - 23)
 │ │ │ ┌───────── day of month (1 - 31)
 │ │ │ │ ┌─────── month        (1 - 12 or JAN - DEC)
 │ │ │ │ │ ┌───── day of week  (1 - 7 or SUN - SAT)
 │ │ │ │ │ │ ┌─── year         (1970 - 2099 or empty)
 │ │ │ │ │ │ │
 * * * * * ? *

The asterisks and question mark represent all positions in a cron expression,
from the smallest unit - a second - on the left to the largest - a year - on the right.
The values in the parentheses display the possible values for each position.
Each position also has a set of special characters that can be used there,
for example for wildcards and ranges.
