#
# Copyright © 2018 Scriptinator (support@scriptinator.io)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

spring:
  thymeleaf:
    mode: HTML
  jpa:
   hibernate:
     ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/scriptinator?useSSL=false
    username: root
    password: root
  mail:
    host: localhost
#   G-Suite Example
#
#   Note: This requires an authorized ip address
#
#    host: smtp-relay.gmail.com
#    port: 587
#    from: Support <user@domain.com>
#    properties:
#      mail.transport.protocol: smtp
#      mail.smtp.auth: false
#      mail.smtp.starttls.enable: true
