server:
  error:
    whitelabel:
      enabled: false
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/scriptinator?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  thymeleaf:
    mode: HTML